# Generated by Django 5.2.11 on 2026-03-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylistservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
