# Generated by Django 5.2.11 on 2026-03-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_stylistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylistprofile',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='other',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='stylist_pics/'),
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='specialties',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
